name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install npm dependencies
        run: npm install
      - name: Create .env file
        run: |
          echo "PUBLIC_FB_API_KEY=${{ secrets.PUBLIC_FB_API_KEY }}" >> .env
          echo "PUBLIC_FB_AUTH_DOMAIN=${{ secrets.PUBLIC_FB_AUTH_DOMAIN }}" >> .env
          echo "PUBLIC_FB_PROJECT_NAME=${{ secrets.PUBLIC_FB_PROJECT_NAME }}" >> .env
          echo "PUBLIC_FB_STORAGE_BUCKET=${{ secrets.PUBLIC_FB_STORAGE_BUCKET }}" >> .env
          echo "PUBLIC_FB_MESSAGING_SENDER_ID=${{ secrets.PUBLIC_FB_MESSAGING_SENDER_ID }}" >> .env
          echo "PUBLIC_FB_APP_ID=${{ secrets.PUBLIC_FB_APP_ID }}" >> .env
      - name: Build the project
        run: npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_VIOLEX_APP }}'
          channelId: live
          projectId: violex-app
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
